theme: jekyll-theme-slate
title: Welcome to the Math Corner!
description: A place for Mr. Kong to put some Mathematics stuff.

[DSE Compulsory Part](https://math-kongsir.github.io/dse-math/compulsory)
